version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - run:
          name: dependancies
          command: yarn
      - run:
          name: test
          command: yarn test
