version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./yarn-installations
      - run:
          name: Test
          command: yarn test
